* Apps
** CoMD
*** Brief description 
CoMD is a reference implementation of typical classical molecular dynamics algorithms and workloads.
*** Build and run  
#+BEGIN_SRC sh :tangle bin/ECP_CoMD.sh
     export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
     export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
     export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     
     echo "Clean up the place" 
     set -exu
     mkdir -p Benchmarks/ECP/ 
     cd Benchmarks/ECP/
     echo "Checkout or update the git containing the source code"
     if [ -e CoMD ] ; then
        cd CoMD ; git reset --hard master ; git clean -dfx ; git pull ; cd ..
     else
        git clone --depth=1 https://github.com/ECP-copa/CoMD.git
     fi

     echo "Install the modified sources"
     cd CoMD/src-mpi/
     cp ../../../../src/ECP/CoMD/* ./

     echo "Compile it" 
     make 
     cd ../examples/
     cp ../../../../src/common/* ./

     echo "Run it"
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ../bin/CoMD-mpi -e -i 4 -j 2 -k 1 -x 40 -y 40 -z 40

 #+END_SRC

** AMG
*** Brief description 
AMG is a parallel algebraic multigrid solver for linear systems arising from
problems on unstructured grids.  The driver provided with AMG builds linear 
systems for various 3-dimensional problems.
*** Build and run 
#+BEGIN_SRC sh :tangle bin/ECP_AMG.sh
     export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
     export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
     export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     
     echo "Clean up the place" 
     set -exu
     mkdir -p Benchmarks/ECP/ 
     cd Benchmarks/ECP/
     echo "Checkout or update the git containing the source code"
     if [ -e AMG ] ; then
        cd AMG ; git reset --hard master ; git clean -dfx ; git pull ; cd ..
     else
        git clone --depth=1 https://github.com/LLNL/AMG.git
     fi

     echo "Install the modified sources"
     cp ../../src/ECP/AMG/* ./AMG/

     echo "Compile it" 
     cd AMG/
     make veryclean
     make
     cp ../../../src/common/* ./test/
     cd test/

     echo "Run it"
     smpirun -np 4 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./amg

 #+END_SRC

** Sw4lite
*** Brief description 
Sw4lite is a bare bone version of SW4 (Github) intended for testing performance optimizations in a few important numerical kernels of SW4.
*** Build and run 
#+BEGIN_SRC sh :tangle bin/ECP_sw4lite.sh
     export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
     export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
     export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     
     echo "Clean up the place" 
     set -exu
     mkdir -p Benchmarks/ECP/ 
     cd Benchmarks/ECP/
     echo "Checkout or update the git containing the source code"
     if [ -e sw4lite ] ; then
        cd sw4lite ; git reset --hard master ; git clean -dfx ; git pull ; cd ..
     else
        git clone --depth=1 https://github.com/geodynamics/sw4lite.git
     fi

     echo "Install the modified sources"
     cp -f ../../src/ECP/sw4lite/pointsource.in ./sw4lite/tests/pointsource/
     cd sw4lite
     sed -i -e "s/\mpicxx/\smpicxx/g" Makefile
     sed -i -e "s/\mpic++/\smpicxx/g" Makefile
     sed -i -e "s/\mpif90/\smpiff/g" Makefile

     echo "Compile it"
     make openmp=no
     cp ../../../src/common/* ./optimize/
     cd optimize/
     
     smpirun -np 16 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./sw4lite ../tests/pointsource/pointsource.in

 #+END_SRC

** QuickSilver
*** Brief description 
Quicksilver is a proxy application that represents some elements of the Mercury workload by solving a simpliﬁed dynamic monte carlo particle transport problem.
*** Build and run 
#+BEGIN_SRC sh :tangle bin/ECP_quicksilver.sh
     export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
     export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
     export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     
     echo "Clean up the place" 
     set -exu
     mkdir -p Benchmarks/ECP/ 
     cd Benchmarks/ECP/
     echo "Checkout or update the git containing the source code"
     if [ -e Quicksilver ] ; then
        cd Quicksilver ; git reset --hard master ; git clean -dfx ; git pull ; cd ..
     else
        git clone --depth=1 https://github.com/LLNL/Quicksilver.git
     fi

     echo "Install the modified sources"
     cp ../../src/common/* ./Quicksilver/src/
     cp ../../src/ECP/Quicksilver/* ./Quicksilver/src/
     cd Quicksilver/src/

     echo "Compile it"
     make

     echo "Run it"
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./qs

 #+END_SRC

** SimpleMOC
*** Brief description 
The purpose of this mini-app is to demonstrate the performance characterterics and viability of the Method of Characteristics (MOC)
for 3D neutron transport calculations in the context of full scale light water reactor simulation.
*** Build and run 
#+BEGIN_SRC sh :tangle bin/ECP_SimpleMOC.sh
     export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
     export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
     export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     
     echo "Clean up the place" 
     set -exu
     mkdir -p Benchmarks/ECP/
     cd Benchmarks/ECP/
     echo "Checkout or update the git containing the source code"
     if [ -e SimpleMOC ] ; then
        cd SimpleMOC ; git reset --hard master ; git clean -dfx ; git pull ; cd ..
     else
        git clone --depth=1 https://github.com/ANL-CESAR/SimpleMOC.git
     fi

     echo "Install the modified sources"
     cp ../../src/common/* ./SimpleMOC/src/
     cp ../../src/ECP/SimpleMOC/* ./SimpleMOC/src/
     cd SimpleMOC/src/

     echo "Compile it"
     make

     echo "Run it"
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./SimpleMOC -i input.in

 #+END_SRC
 
* Emacs settings
# Local Variables:
# eval:    (org-babel-do-load-languages 'org-babel-load-languages '( (shell . t) (R . t) (perl . t) (ditaa . t) ))
# eval:    (setq org-confirm-babel-evaluate nil)
# eval:    (setq org-alphabetical-lists t)
# eval:    (setq org-src-fontify-natively t)
# eval:    (add-hook 'org-babel-after-execute-hook 'org-display-inline-images) 
# eval:    (add-hook 'org-mode-hook 'org-display-inline-images)
# eval:    (add-hook 'org-mode-hook 'org-babel-result-hide-all)
# eval:    (setq org-babel-default-header-args:R '((:session . "org-R")))
# eval:    (setq org-export-babel-evaluate nil)
# eval:    (setq ispell-local-dictionary "american")
# eval:    (setq org-export-latex-table-caption-above nil)
# eval:    (eval (flyspell-mode t))
# End:
